version: '3.8'

services:
  postgres:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

  bot:
    build:
      context: ./bot
    container_name: bot
    env_file: .env
    volumes:
      - ./bot:/app
    working_dir: /app
    command: python3 main.py
    depends_on:
      - postgres
    networks:
      - app-network

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile.scraper
    container_name: scraper
    volumes:
      - ./scraper:/app
    working_dir: /app
    command: python3 scrapergithub_parser.py
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
