version: '3.8'

services:
  postgres:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

  bot:
    build: ./bot
    env_file: .env
    environment:
      - SPRING_DATASOURCE_URL=${BOT_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${BOT_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${BOT_DATASOURCE_PASSWORD}
    ports:
      - "${BOT_SERVER_PORT}:${BOT_SERVER_PORT}"
    depends_on:
      - postgres
    networks:
      - app-network

  scrapper:
    build: ./scrapper
    env_file: .env
    environment:
      - SPRING_DATASOURCE_URL=${SCRAPPER_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SCRAPPER_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SCRAPPER_DATASOURCE_PASSWORD}
    ports:
      - "${SCRAPPER_SERVER_PORT}:${SCRAPPER_SERVER_PORT}"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
